import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className="bg-blue-900 h-[70px] text-2xl ">
           <Link className="m-10" href="/">Home</Link>
          <Link className="m-10" href="/about">About</Link>
          <Link className="m-10"href="/contact">Contact</Link>
          <Link className="m-10"href="/users">Users</Link>
        </header>

        {/* 👇 This is where your pages (like /about) will be rendered */}
        {children}
      </body>
    </html>
  );
}

